# Generated by Django 3.2.25 on 2024-11-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cimg',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
    ]
