# Generated by Django 3.2.25 on 2024-11-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
