# Generated by Django 3.2.25 on 2024-11-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
