# Generated by Django 3.2.25 on 2024-11-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20241129_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
