# Generated by Django 3.2.25 on 2024-12-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
