# Generated by Django 3.2.25 on 2024-12-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_active',
            new_name='active',
        ),
    ]
