# Generated by Django 3.2.25 on 2025-01-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_available_count',
        ),
    ]
