# Generated by Django 3.2.25 on 2025-01-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_product_product_available_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available_count',
            field=models.IntegerField(default=0),
        ),
    ]
