# Generated by Django 3.2.25 on 2025-01-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_product_product_available_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
