# Generated by Django 3.2.25 on 2024-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpayment', '0003_auto_20241224_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
