# Generated by Django 3.2.25 on 2024-12-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_coupon'),
        ('orderpayment', '0004_myorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
