# Generated by Django 3.2.25 on 2024-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpayment', '0005_myorders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
    ]
