# Generated by Django 3.2.25 on 2025-01-02 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orderpayment', '0006_alter_myorders_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
