# Generated by Django 3.2.25 on 2025-01-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpayment', '0007_myorders_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
